#' @title Hierarchical Clustering of Samples Using Bray-Curtis Distance
#' @description Performs hierarchical clustering of samples in a phyloseq object using Bray-Curtis distance (or another specified distance) on relative abundances, and plots a heatmap faceted by a sample metadata variable.
#' @param phobj A `phyloseq` object containing microbiome data.
#' @param variable Character string specifying the sample metadata variable to use for coloring the dendrogram and labeling the heatmap. Default: 'Condition'
#' @param renamestr Character string to replace prefix "X" in sample names after transpose (if needed). Default: ''
#' @param dist_type Distance metric to compute sample distances. Default: 'bray'
#' @param clust_method Clustering method to use for hierarchical clustering. Default: 'ward.D2'
#' @return A list containing:
#' \item{ward}{A dendrogram object of the hierarchical clustering}
#' \item{hmplot}{A `ggplot` heatmap plot object generated by `phyloseq::plot_heatmap`}
#' @details
#' The function first transforms the OTU counts to relative abundances,
#' computes a sample distance matrix using the specified distance method,
#' performs hierarchical clustering, colors dendrogram labels by the grouping variable,
#' and finally produces a heatmap faceted by the grouping variable.
#' @examples
#' \dontrun{
#' if(interactive()){
#'   library(phyloseq)
#'   data(GlobalPatterns)
#'
#'   # Perform clustering faceted by SampleType
#'   res <- clusterBrayCurtis(
#'     phobj = GlobalPatterns,
#'     variable = "SampleType",
#'     renamestr = "",
#'     dist_type = "bray",
#'     clust_method = "ward.D2"
#'   )
#'
#'   # Plot dendrogram
#'   plot(res$ward)
#'
#'   # Print heatmap
#'   print(res$hmplot)
#' }
#' }
#' @seealso
#' \code{\link[phyloseq]{transform_sample_counts}}, \code{\link[phyloseq]{otu_table}}, \code{\link[phyloseq]{distance}}, \code{\link[phyloseq]{sample_data}}, \code{\link[phyloseq]{plot_heatmap}}
#' @rdname clusterBrayCurtis
#' @export
#' @importFrom phyloseq transform_sample_counts otu_table distance sample_data plot_heatmap
#' @importFrom dendextend labels_colors
#' @importFrom stats order.dendrogram
clusterBrayCurtis <- function(phobj, variable="Condition", renamestr="",
                              dist_type="bray", clust_method="ward.D2"){
  ps_rel_abund = phyloseq::transform_sample_counts(phobj, function(x){x / sum(x)})
  ps_rel_otu <- data.frame(phyloseq::otu_table(ps_rel_abund))
  ps_rel_otu <- t(ps_rel_otu)
  rownames(ps_rel_otu) <- gsub("^X", renamestr, rownames(ps_rel_otu))
  #bc_dist <- vegan::vegdist(ps_rel_otu, method = dist_type)
  bc_dist <- phyloseq::distance(physeq = phobj, method = dist_type)

  #Save as dendrogram
  ward <- as.dendrogram(hclust(bc_dist, method = clust_method))
  #Provide color codes
  meta <- data.frame(phyloseq::sample_data(ps_rel_abund))
  levv <- unique(meta[, variable])
  colorCode <- grDevices::colorRampPalette( wesanderson::wes_palette("Royal1"))(length(levv))
  names(colorCode) <- levv
  dendextend::labels_colors(ward) <- colorCode[meta[, variable]][stats::order.dendrogram(ward)]

  hmplot <- phyloseq::plot_heatmap(ps_rel_abund, sample.label=variable)
  return(list("ward"=ward, "hmplot"=hmplot))
}
