#' @title Perform Beta Dispersion Tests Across Sample Metadata Variables
#' @description Computes beta diversity distance matrix for a phyloseq object, then tests for differences in dispersion (variance) across levels of each metadata variable, excluding specified variables.
#' @param phobj A \code{phyloseq} object containing microbiome data and sample metadata.
#' @param dist_method Distance metric to calculate beta diversity (passed to \code{\link[phyloseq]{distance}}). Default: "bray".
#' @param exclude_vars Character vector of sample metadata variable names to exclude from testing (e.g., sample IDs). Default: \code{c("sampleID")}.
#' @param outname File path to save the output results as a TSV file.
#' @return A data.frame summarizing the beta dispersion test results, with columns for the variable name, F statistic, and p-value.
#' @details
#' For each sample metadata variable (except those excluded), this function calculates the beta dispersion
#' (variance of distances to group centroids) using \code{\link[vegan]{betadisper}} on the distance matrix
#' generated by \code{\link[phyloseq]{distance}}. Significance is assessed by permutation tests
#' using \code{\link[vegan]{permutest}}. Results are saved to a TSV file and returned as a data.frame.
#'
#' @examples
#' \dontrun{
#' if(interactive()){
#'   library(phyloseq)
#'   library(vegan)
#'   data(GlobalPatterns)
#'   res <- makeBetaDispTests(GlobalPatterns, dist_method = "bray",
#'                           exclude_vars = c("sampleID"),
#'                           outname = "beta_dispersion_results.tsv")
#'   print(res)
#' }
#' }
#' @seealso \code{\link[phyloseq]{distance}}, \code{\link[vegan]{betadisper}}, \code{\link[vegan]{permutest}}
#' @rdname makeBetaDispTests
#' @export
#' @importFrom phyloseq distance sample_data
#' @importFrom vegan betadisper permutest
#' @importFrom readr write_tsv
makeBetaDispTests<- function(phobj, dist_method = "bray",
                             exclude_vars = c("sampleID"),
                             outname){

  braydist <- phyloseq::distance(phobj, method = dist_method)
  sampledf <- data.frame(sample_data(phobj))
  vars2test <- names(sampledf)[! names(sampledf) %in% exclude_vars]
  res <- data.frame()
  for(var in vars2test){
    beta <- betadisper(braydist, sampledf[, var])
    betaper <- permutest(beta)
    aux <- data.frame(variable = var,
                      F = betaper$tab$F[1],
                      p = betaper$tab$`Pr(>F)`[1])
    res <- rbind(res, aux)
  }
  write_tsv(res, file=outname)
  return(res)
}
