#' @title Generate Correlation Heatmap Between Two Matrices
#' @description Computes pairwise correlations between columns of two matrices and plots a heatmap annotated with significance levels.
#' @param mat1 Numeric matrix or data frame. Columns represent variables/features (e.g., ASVs, taxa) for correlation.
#' @param mat2 Numeric matrix or data frame. Columns represent variables/features to correlate with those in \code{mat1}.
#' @param cormethod Correlation method to use. One of "pearson" (default), "spearman", or "kendall".
#' @param pval Numeric threshold for significance (default 0.05). Only rows (variables in \code{mat1}) with at least one correlation p-value below this threshold are included, unless \code{select_asvs} is provided.
#' @param select_asvs Character vector of row names (variables in \code{mat1}) to explicitly include in the heatmap. Overrides \code{pval} filtering.
#' @param outdir Output directory path where the heatmap PDF will be saved. Default is current directory ("./").
#' @param name Filename prefix for output PDF (default: "corrHeatmap").
#' @param clust Logical indicating whether to cluster rows and columns (default TRUE).
#' @param order_rows Character vector specifying the order of rows if clustering is disabled (default empty).
#' @param order_cols Character vector specifying the order of columns if clustering is disabled (default empty).
#' @return A list containing:
#' \item{hm}{The pheatmap object (invisible) generated by the function.}
#' \item{asvs}{The vector of selected ASVs (rows) included in the heatmap.}
#' \item{cormat}{The correlation matrix subsetted and possibly reordered for plotting.}
#' \item{pvals}{Matrix of p-values corresponding to the correlations.}
#' \item{cor_ptext}{Matrix of significance symbols corresponding to p-values.}
#' @details
#' The function computes correlation coefficients and p-values between every pair of columns from \code{mat1} and \code{mat2}.
#' It filters variables from \code{mat1} based on significance thresholds or a user-provided selection.
#' The resulting heatmap includes correlation values annotated with significance stars, enhancing interpretability.
#' @examples
#' \dontrun{
#' if(interactive()){
#'   mat1 <- matrix(rnorm(100*10), nrow=100, ncol=10)
#'   colnames(mat1) <- paste0("VarA", 1:10)
#'   mat2 <- matrix(rnorm(100*8), nrow=100, ncol=8)
#'   colnames(mat2) <- paste0("VarB", 1:8)
#'   result <- makeCorrelationHeatmap(mat1, mat2, cormethod="spearman", pval=0.05)
#' }
#' }
#' @seealso \code{\link[tidyr]{spread}}, \code{\link[pheatmap]{pheatmap}}
#' @rdname makeCorrelationHeatmap
#' @export
#' @importFrom tidyr spread
#' @importFrom pheatmap pheatmap
makeCorrelationHeatmap <- function(mat1, mat2, cormethod="pearson",
                                   pval=0.05, select_asvs=c(), outdir="./", name="corrHeatmap",
                                   clust=T, order_rows = c(), order_cols = c()){
  # select_asvs: plot these ASVs. Overrides pval
  # pval: plot ASVs with any correlation >  than this threshold
  cormat <- cor(mat1, mat2, method=cormethod)
  cor_pval <- expand.grid(colnames(mat1), colnames(mat2)) %>%
    rowwise() %>%
    mutate(pval = cor.test(mat1[, Var1], mat2[, Var2], method=cormethod)$p.value) %>%
    ungroup() %>%
    tidyr::spread(Var2, pval) %>%
    column_to_rownames("Var1") %>%
    as.matrix()
  cor_pval <- cor_pval[rownames(cormat), colnames(cormat)]


  if(length(select_asvs) > 0){
    cormat <- cormat[select_asvs, ]
    cor_pval <- cor_pval[select_asvs, ]
  }else if(pval < 1.0){
    select_asvs <- cor_pval %>% apply(MAR=1, function(x) any(x < pval)) %>% which() %>% names
    cormat <- cormat[select_asvs, ]
    cor_pval <- cor_pval[select_asvs, ]
  }
  cor_ptext <- getSignif2(cor_pval)
  if(! clust){
    cormat <- cormat[order_rows, order_cols]
    cor_ptext <- cor_ptext[order_rows, order_cols]
    cor_pval <- cor_pval[order_rows, order_cols]
  }

  cormat <- cormat %>% t
  cor_ptext <- cor_ptext %>% t
  cor_pval <- cor_pval %>% t

  oname <- paste0(outdir, "/", name, ".pdf")
  fontsize_row = 16 - nrow(cormat) / 15
  fontsize_col = 16 - ncol(cormat) / 15

  pheatmap(cormat, display_numbers = cor_ptext, filename=oname,
           width = 20, height = 6,
           fontsize_row = fontsize_row,
           fontsize_number = 16,
           fontsize_col = fontsize_col,
           cluster_rows = clust, cluster_cols = clust
  )
  tmp <- tryCatch(dev.off(), error=function(x){})
  hm <- pheatmap(cormat, display_numbers = cor_ptext,
                 filename=oname,
                 width = 20, height = 6,
                 fontsize_row = fontsize_row,
                 fontsize_number = 16,
                 fontsize_col = fontsize_col,
                 cluster_rows = clust, cluster_cols = clust
  )
  return(list(hm=hm, asvs=select_asvs, cormat=cormat,
              pvals=cor_pval, cor_ptext=cor_ptext))
}
