#' @title Write Multiple ggplot2 Plots to PDF Files
#'
#' @description
#' Saves a list of ggplot2 plots to individual PDF files or a single combined PDF.
#'
#' @param plotlist A named list of ggplot2 plot objects to be saved.
#' @param name A base name to use for the output file(s).
#' @param outdir The output directory where the PDF file(s) will be written.
#' @param w Width of the PDF plot(s), in inches. Default: \code{12}.
#' @param h Height of the PDF plot(s), in inches. Default: \code{7}.
#' @param separate Logical; if \code{TRUE}, writes each plot to a separate PDF file. If \code{FALSE}, all plots are written to a single PDF. Default: \code{FALSE}.
#' @param opt Optional list of options passed to \code{getNullPlot()} in case a plot fails. Default: \code{list()}.
#'
#' @return
#' No return value. Side effect: generates PDF files with the specified plots.
#'
#' @details
#' If a plot in the list fails to render, a fallback plot generated by \code{getNullPlot(opt, plotname)} is printed instead.
#' The function creates the output directory if it does not exist.
#'
#' @examples
#' \dontrun{
#' if(interactive()){
#'  # Save all plots to a single PDF
#'   WriteManyPlots(my_plot_list, name = "analysis", outdir = "results")
#'
#'   # Save each plot to its own PDF
#'   WriteManyPlots(my_plot_list, name = "analysis", outdir = "results", separate = TRUE)
#'
#'  }
#' }
#' @rdname WriteManyPlots
#' @export
WriteManyPlots <- function(plotlist, name, outdir, w=12, h=7, separate=F, opt=list()){
  if(! dir.exists(outdir)){dir.create(outdir)}
  if(separate){
    for(p in names(plotlist)){
      fname = paste0(outdir, "/", name, "_", p, ".pdf")
      pdf(fname, width=w, height=g)
      tryCatch({print(plotlist[[p]])}, error = function(x){print(getNullPlot(opt, p))})
      dev.off()
    }
  }else{
    fname = paste0(outdir, "/", name, "_all.pdf")
    pdf(fname, width=w, height=h)
    for(p in names(plotlist)){
      tryCatch({print(plotlist[[p]])}, error = function(x){print(getNullPlot(opt, p))})
    }
    dev.off()
  }
}
